main = ".open-next/worker.js"
name = "fixchef"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "fixchef"

[images]
binding = "IMAGES"

[[d1_databases]]
binding = "DB"
database_name = "fixchef"
database_id = "03bb856b-d82a-48d9-9042-8f289528030d"
