import type { Metadata } from 'next';
import Link from 'next/link';
import Breadcrumb from '@/components/Breadcrumb';

export const metadata: Metadata = {
  title: 'Terms of Use',
  description: 'Read the FixChef Terms of Use — the rules and guidelines for using our recipe website.',
  alternates: { canonical: 'https://fixchef.com/terms' },
};

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-12">
      <Breadcrumb items={[{ label: 'Home', href: '/' }, { label: 'Terms of Use', href: '/terms' }]} />

      <h1 className="text-4xl font-display font-bold text-gray-900 mb-2">Terms of Use</h1>
      <p className="text-sm text-gray-400 mb-10">Last updated: April 2026</p>

      <div className="space-y-8 text-gray-700 leading-relaxed">

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing or using FixChef (&ldquo;the Site&rdquo;), you agree to be bound by these
            Terms of Use. If you do not agree, please do not use the Site.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">2. Use of the Site</h2>
          <p>You may use FixChef for personal, non-commercial purposes. You agree not to:</p>
          <ul className="list-disc pl-6 mt-3 space-y-1">
            <li>Scrape, crawl, or systematically download content without permission</li>
            <li>Reproduce or republish recipes or content without attribution</li>
            <li>Use the Site in any way that could damage, disable, or impair it</li>
            <li>Attempt to gain unauthorised access to any part of the Site</li>
            <li>Use automated tools to interact with the AI chatbot at scale</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">3. Intellectual Property</h2>
          <p>
            All content on FixChef — including recipes, text, images, and code — is owned by or
            licensed to FixChef. Recipe photography is sourced from Unsplash under their licence.
            Videos are embedded from YouTube and remain the property of their respective creators.
          </p>
          <p className="mt-3">
            You may share links to our recipes freely. You may not copy and republish full recipe
            content on other websites or publications without written permission.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">4. AI Chatbot Disclaimer</h2>
          <p>
            The AI cooking assistant on recipe pages is provided for convenience. Responses are
            generated by an AI model and may occasionally be inaccurate. Always use your own
            judgement when following cooking advice, especially regarding food safety, allergies,
            and dietary restrictions. FixChef is not liable for any harm arising from following
            AI-generated advice.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Nutritional Information</h2>
          <p>
            Nutritional values displayed on recipe pages are estimates calculated from standard
            ingredient databases. They are provided for informational purposes only and should not
            be used as a substitute for professional dietary advice. Actual values may vary based
            on specific ingredients, brands, and preparation methods used.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Third-Party Links and Embeds</h2>
          <p>
            The Site contains links to and embeds from third-party services (YouTube, Unsplash, etc.).
            We are not responsible for the content or privacy practices of those services. Use of
            third-party services is subject to their own terms and policies.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Advertising</h2>
          <p>
            FixChef displays advertisements via Google AdSense. Advertisements are clearly
            distinguished from editorial content. We do not endorse any advertised products or
            services. Clicking on ads is at your own discretion.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">8. Disclaimer of Warranties</h2>
          <p>
            The Site is provided &ldquo;as is&rdquo; without warranties of any kind. We do not
            guarantee that the Site will be uninterrupted, error-free, or free of viruses. Use of
            the Site is at your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">9. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, FixChef shall not be liable for any indirect,
            incidental, or consequential damages arising from your use of the Site or its content.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">10. Changes to These Terms</h2>
          <p>
            We may update these Terms at any time. Changes will be posted on this page with an
            updated date. Continued use of the Site after changes constitutes acceptance of the
            revised Terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">11. Contact</h2>
          <p>
            Questions about these Terms? Contact us at{' '}
            <a href="mailto:hello@fixchef.com" className="text-orange-500 hover:underline">
              hello@fixchef.com
            </a>{' '}
            or visit our <Link href="/contact" className="text-orange-500 hover:underline">Contact page</Link>.
          </p>
        </section>

      </div>
    </main>
  );
}
